name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and Push Images udagram-api-feed image
        id: build_push_1
        run: |
          docker build . -f ./udagram-api-feed/Dockerfile -t huynhnguyen9797/udagram-api-feed:v1 
          docker push huynhnguyen9797/udagram-api-feed:v1 
      - name: Build and Push Images udagram-api-user image
        id: build_push_2
        run: |
          docker build . -f ./udagram-api-user/Dockerfile -t huynhnguyen9797/udagram-api-user:v1 
          docker push huynhnguyen9797/udagram-api-user:v1
      - name: Build and Push Images udagram-frontend image
        id: build_push_3
        run: |
          docker build . -f ./udagram-frontend/Dockerfile -t huynhnguyen9797/udagram-frontend:v1 
          docker push huynhnguyen9797/udagram-frontend:v1
      - name: Build and Push Images udagram-reverseproxy image
        id: build_push_4
        run: |
          docker build . -f ./udagram-reverseproxy/Dockerfile -t huynhnguyen9797/reverseproxy:v1 
          docker push huynhnguyen9797/reverseproxy:v1
    
